# Generated by Django 4.2.26 on 2025-11-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_alter_cocktail_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
