# Generated by Django 4.2.26 on 2025-11-14 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_remove_cocktail_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cocktail',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
