# Generated by Django 4.2.26 on 2025-11-14 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cocktails', '0005_remove_cocktail_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='garnish',
            field=models.TextField(blank=True, help_text='Optional. Free text.', null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredients',
            field=models.TextField(help_text='One ingredient per line.'),
        ),
    ]
