# Generated by Django 4.2.26 on 2025-11-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_rename_comments_comment_alter_cocktail_garnish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_publish',
        ),
    ]
